[package]
name = "exstatic"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "exstatic"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.35.1", default-features = false, features = ["nif_version_2_17"] }
statrs = "0.18.0"
